[package]
name = "rzfs_lib"
version = "0.0.0"
edition = "2021"
description = "Rust library to parse ZFS data structures."
license = "GPL-2.0+ OR MIT"

[lib]
name = "rzfs_lib"

[features]
default = ["std"]
std = []
